version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Mashal/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    # depends_on:
    #   - db

  # db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "YourStrong!Passw0rd"
  #     ACCEPT_EULA: "Y"
  #   ports:
  #     - "1433:1433"